version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: sidilec-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: controle_Qualite
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - sidilec-network

  backend:
    build: .
    container_name: backend-sidilec
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/controle_Qualite?serverTimezone=UTC&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - sidilec-network

volumes:
  mysql_data:

networks:
  sidilec-network:
    driver: bridge
